# Generated by Django 5.0.4 on 2024-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0002_course_remove_student_course_remove_teacher_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
