# Generated by Django 5.0.4 on 2024-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0003_alter_module_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('TE', 'Teacher')], max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('TE', 'Teacher')], max_length=2),
        ),
    ]
