# Generated by Django 5.0.4 on 2024-04-24 18:22

from django.db import migrations


def migrate_roles(apps, schema_editor):
    Student = apps.get_model('Centre', 'Student')
    Teacher = apps.get_model('Centre', 'Teacher')

    STUDENT = 'ST'
    TEACHER = 'TE'

    for student in Student.objects.all():
        student.role = STUDENT
        student.save()

    for teacher in Teacher.objects.all():
        teacher.role = TEACHER
        teacher.save()


class Migration(migrations.Migration):
    dependencies = [
        ('Centre', '0004_student_role_teacher_role'),
    ]

    operations = [
        migrations.RunPython(migrate_roles),
    ]
