# Generated by Django 5.0.4 on 2024-04-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0005_auto_20240424_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastname1',
            new_name='first_lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname2',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='second_lastname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname1',
            new_name='first_lastname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname2',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='second_lastname',
        ),
    ]
